DateTime now = DateTime.Now;
Console.WriteLine(now);
string time = "1970 yil 1-yanvar";
Console.WriteLine(time);
int age = 70;
Console.WriteLine($"{age} yosh");
float salary = 35.5F;
Console.WriteLine($"{salary}$");
string job = "Max Developer";
Console.WriteLine(job);